config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"
  get 'search/autocomplete' => "search#autocomplete", as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  # Get all keys of user
  get ':username.keys' => 'profiles/keys#get_keys' , constraints: { username: /.*/ }

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }, via: [:get, :post]

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/api/:category'  => 'help#api', as: 'help_api_file'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'
  get 'help/shortcuts'
  get 'help/security'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    root to: "projects#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_teams_update
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resources :broadcast_messages, only: [:index, :create, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      member do
        put :transfer
      end
    end

    root to: "dashboard#index"
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :history
      get :design

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resources :groups, only: [:index] do
        member do
          delete :leave
        end
      end
      resource :avatar, only: [:destroy]
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }, via: :get



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :members
    end

    resources :users_groups, only: [:create, :update, :destroy]
    scope module: :groups do
      resource :avatar, only: [:destroy]
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations , passwords: :passwords}

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[a-zA-Z.0-9_\-]+\/[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      post :archive
      post :unarchive
      get :autocomplete_sources
      get :import
      put :retry_import
    end

    scope module: :projects do
      resources :blob,      only: [:show, :destroy], constraints: {id: /.+/}
      resources :raw,       only: [:show], constraints: {id: /.+/}
      resources :tree,      only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
      resources :edit_tree, only: [:show, :update], constraints: { id: /.+/ }, path: 'edit' do
        post :preview, on: :member
      end
      resources :new_tree,  only: [:show, :update], constraints: {id: /.+/}, path: 'new'
      resources :commit,    only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
      resources :commits,   only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
      resources :compare,   only: [:index, :create]
      resources :blame,     only: [:show], constraints: {id: /.+/}
      resources :network,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      resources :graphs,    only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}

      match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

        resources :snippets, constraints: {id: /\d+/} do
          member do
            get "raw"
          end
        end

      resources :wikis, only: [:show, :edit, :destroy, :create], constraints: {id: /[a-zA-Z.0-9_\-\/]+/} do
        collection do
          get :pages
          put ':id' => 'wikis#update'
          get :git_access
        end

        member do
          get "history"
        end
      end

      resource :wall, only: [:show], constraints: {id: /\d+/} do
        member do
          get 'notes'
        end
      end

      resource :repository, only: [:show] do
        member do
          get "stats"
          get "archive", constraints: { format: Gitlab::Regex.archive_formats_regex }
        end
      end

      resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
        member do
          get :test
        end
      end

      resources :deploy_keys, constraints: {id: /\d+/} do
        member do
          put :enable
          put :disable
        end
      end

      resources :branches, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex } do
        collection do
          get :recent, constraints: { id: Gitlab::Regex.git_reference_regex }
        end
      end

      resources :tags, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }
      resources :protected_branches, only: [:index, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }

      resources :refs, only: [] do
        collection do
          get "switch"
        end

        member do
          # tree viewer logs
          get "logs_tree", constraints: { id: Gitlab::Regex.git_reference_regex }
          get "logs_tree/:path" => "refs#logs_tree",
            as: :logs_file,
            constraints: {
              id:   Gitlab::Regex.git_reference_regex,
              path: /.*/
            }
        end
      end

      resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
        member do
          get :diffs
          post :automerge
          get :automerge_check
          get :ci_status
        end

        collection do
          get :branch_from
          get :branch_to
          get :update_branches
        end
      end

      resources :hooks, only: [:index, :create, :destroy], constraints: {id: /\d+/} do
        member do
          get :test
        end
      end

      resources :team, controller: 'team_members', only: [:index]
      resources :milestones, except: [:destroy], constraints: {id: /\d+/}

      resources :labels, only: [:index] do
        collection do
          post :generate
        end
      end

      resources :issues, constraints: {id: /\d+/}, except: [:destroy] do
        collection do
          post  :bulk_update
        end
      end

      resources :team_members, except: [:index, :edit], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ } do
        collection do
          delete :leave

          # Used for import team
          # from another project
          get :import
          post :apply_import
        end
      end

      resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
        member do
          delete :delete_attachment
        end

        collection do
          post :preview
        end
      end
    end
  end

  get ':id' => "groups#show", constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}

  root to: "dashboard#show"
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::ApplicationController
  before_filter :group, only: [:edit, :show, :update, :destroy, :project_update, :project_teams_update]

  def index
    @groups = Group.order('name ASC')
    @groups = @groups.search(params[:name]) if params[:name].present?
    @groups = @groups.page(params[:page]).per(20)
  end

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(params[:group])
    @group.path = @group.name.dup.parameterize if @group.name

    if @group.save
      @group.add_owner(current_user)
      redirect_to [:admin, @group], notice: 'Group was successfully created.'
    else
      render "new"
    end
  end

  def update
    if @group.update_attributes(params[:group])
      redirect_to [:admin, @group], notice: 'Group was successfully updated.'
    else
      render "edit"
    end
  end

  def project_teams_update
    @group.add_users(params[:user_ids].split(','), params[:group_access])

    redirect_to [:admin, @group], notice: 'Users were successfully added.'
  end

  def destroy
    @group.destroy

    redirect_to admin_groups_path, notice: 'Group was successfully deleted.'
  end

  private

  def group
    @group = Group.find_by(path: params[:id])
  end
end

app/controllers/groups/avatars_controller.rb
class Groups::AvatarsController < ApplicationController
  layout "profile"

  def destroy
    @group = Group.find_by(path: params[:group_id])
    @group.remove_avatar!

    @group.save

    redirect_to edit_group_path(@group)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:show, :issues, :members, :merge_requests]
  respond_to :html
  before_filter :group, except: [:new, :create]

  # Authorize
  before_filter :authorize_read_group!, except: [:new, :create]
  before_filter :authorize_admin_group!, only: [:edit, :update, :destroy]
  before_filter :authorize_create_group!, only: [:new, :create]

  # Load group projects
  before_filter :projects, except: [:new, :create]

  before_filter :default_filter, only: [:issues, :merge_requests]

  layout :determine_layout

  before_filter :set_title, only: [:new, :create]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    @group.path = @group.name.dup.parameterize if @group.name

    if @group.save
      @group.add_owner(current_user)
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render action: "new"
    end
  end

  def show
    @events = Event.in_projects(project_ids)
    @events = event_filter.apply_filter(@events)
    @events = @events.limit(20).offset(params[:offset] || 0)
    @last_push = current_user.recent_push if current_user

    respond_to do |format|
      format.html
      format.json { pager_json("events/_events", @events.count) }
      format.atom { render layout: false }
    end
  end

  def merge_requests
    @merge_requests = MergeRequestsFinder.new.execute(current_user, params)
    @merge_requests = @merge_requests.page(params[:page]).per(20)
    @merge_requests = @merge_requests.preload(:author, :target_project)
  end

  def issues
    @issues = IssuesFinder.new.execute(current_user, params)
    @issues = @issues.page(params[:page]).per(20)
    @issues = @issues.preload(:author, :project)

    respond_to do |format|
      format.html
      format.atom { render layout: false }
    end
  end

  def members
    @project = group.projects.find(params[:project_id]) if params[:project_id]
    @members = group.users_groups

    if params[:search].present?
      users = group.users.search(params[:search]).to_a
      @members = @members.where(user_id: users)
    end

    @members = @members.order('group_access DESC').page(params[:page]).per(50)
    @users_group = UsersGroup.new
  end

  def edit
  end

  def update
    if @group.update_attributes(params[:group])
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @group.destroy

    redirect_to root_path, notice: 'Group was removed.'
  end

  protected

  def group
    @group ||= Group.find_by(path: params[:id])
  end

  def projects
    @projects ||= ProjectsFinder.new.execute(current_user, group: group).sorted_by_activity.non_archived
  end

  def project_ids
    projects.pluck(:id)
  end

  # Dont allow unauthorized access to group
  def authorize_read_group!
    unless @group and (projects.present? or can?(current_user, :read_group, @group))
      if current_user.nil?
        return authenticate_user!
      else
        return render_404
      end
    end
  end

  def authorize_create_group!
    unless can?(current_user, :create_group, nil)
      return render_404
    end
  end

  def authorize_admin_group!
    unless can?(current_user, :manage_group, group)
      return render_404
    end
  end

  def set_title
    @title = 'New Group'
  end

  def determine_layout
    if [:new, :create].include?(action_name.to_sym)
      'navless'
    elsif current_user
      'group'
    else
      'public_group'
    end
  end

  def default_filter
    if params[:scope].blank?
      if current_user
        params[:scope] = 'assigned-to-me'
      else
        params[:scope] = 'all'
      end
    end
    params[:state] = 'opened' if params[:state].blank?
    params[:group_id] = @group.id
  end
end

app/controllers/profiles/groups_controller.rb
class Profiles::GroupsController < ApplicationController
  layout "profile"

  def index
    @user_groups = current_user.users_groups.page(params[:page]).per(20)
  end

  def leave
    @users_group = group.users_groups.where(user_id: current_user.id).first
    if can?(current_user, :destroy, @users_group)
      @users_group.destroy
      redirect_to(profile_groups_path, info: "You left #{group.name} group.")
    else
      return render_403
    end
  end

  private

  def group
    @group ||= Group.find_by(path: params[:id])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def remove_user_from_group_message(group, user)
    "Are you sure you want to remove \"#{user.name}\" from \"#{group.name}\"?"
  end

  def leave_group_message(group)
    "Are you sure you want to leave \"#{group}\" group?"
  end
  
  def should_user_see_group_roles?(user, group)
    if user
      user.is_admin? || group.members.exists?(user_id: user.id)
    else
      false
    end
  end

  def group_head_title
    title = @group.name

    title = if current_action?(:issues)
              "Issues - " + title
            elsif current_action?(:merge_requests)
              "Merge requests - " + title
            elsif current_action?(:members)
              "Members - " + title
            elsif current_action?(:edit)
              "Settings - " + title
            else
              title
            end

    title

  end
end

app/views/groups/_filter.html.haml
= form_tag group_filter_path(entity), method: 'get' do
  %fieldset
    %ul.nav.nav-pills.nav-stacked
      %li{class: ("active" if !params[:status])}
        = link_to group_filter_path(entity, status: nil) do
          Open
      %li{class: ("active" if params[:status] == 'closed')}
        = link_to group_filter_path(entity, status: 'closed') do
          Closed
      %li{class: ("active" if params[:status] == 'all')}
        = link_to group_filter_path(entity, status: 'all') do
          All

  %fieldset
    %legend Projects:
    %ul.nav.nav-pills.nav-stacked
      - @projects.each do |project|
        - unless entities_per_project(project, entity).zero?
          %li{class: ("active" if params[:project_id] == project.id.to_s)}
            = link_to group_filter_path(entity, project_id: project.id) do
              = project.name_with_namespace
              %small.pull-right= entities_per_project(project, entity)
      - if @projects.blank?
        .nothing-here-block This group has no projects yet

  %fieldset
    %hr
    = link_to "Reset", group_filter_path(entity), class: 'btn pull-right'

app/views/groups/_new_group_member.html.haml
= form_for @users_group, url: group_users_groups_path(@group), html: { class: 'form-horizontal users-group-form' } do |f|
  .form-group
    = f.label :user_ids, "People", class: 'control-label'
    .col-sm-10= users_select_tag(:user_ids, multiple: true, class: 'input-large')

  .form-group
    = f.label :group_access, "Group Access", class: 'control-label'
    .col-sm-10= select_tag :group_access, options_for_select(UsersGroup.group_access_roles, @users_group.group_access), class: "project-access-select select2"

  .form-actions
    = f.submit 'Add users into group', class: "btn btn-create"

app/views/groups/_projects.html.haml
.ui-box
  .title
    Projects (#{projects.count})
    - if can? current_user, :manage_group, @group
      %span.pull-right
        = link_to new_project_path(namespace_id: @group.id), class: "btn btn-new" do
          %i.icon-plus
          New project
  %ul.well-list
    - if projects.blank?
      .nothing-here-block This groups has no projects yet
    - projects.each do |project|
      %li.project-row
        = link_to project_path(project), class: dom_class(project) do
          .dash-project-access-icon
            = visibility_level_icon(project.visibility_level)
          %span.str-truncated
            %span.project-name
              = truncate(project.name, length: 25)
          %span.arrow
            %i.icon-angle-right

app/views/groups/edit.html.haml
.row
  .col-md-2
    %ul.nav.nav-pills.nav-stacked.nav-stacked-menu
      %li.active
        = link_to '#tab-edit', 'data-toggle' => 'tab' do
          %i.icon-edit
          Group
      %li
        = link_to '#tab-projects', 'data-toggle' => 'tab' do
          %i.icon-folder-close
          Projects
      %li
        = link_to '#tab-remove', 'data-toggle' => 'tab' do
          %i.icon-remove-sign
          Remove

  .col-md-10
    .tab-content
      .tab-pane.active#tab-edit
        .ui-box
          .title
            %strong= @group.name
            group settings:
          %div.form-holder
            = form_for @group, html: { multipart: true, class: "form-horizontal" }, authenticity_token: true do |f|
              - if @group.errors.any?
                .alert.alert-danger
                  %span= @group.errors.full_messages.first
              .form-group
                = f.label :name, class: 'control-label' do
                  Group name
                .col-sm-10
                  = f.text_field :name, placeholder: "Ex. OpenSource", class: "form-control left"

              .form-group.group-description-holder
                = f.label :description, "Details", class: 'control-label'
                .col-sm-10
                  = f.text_area :description, maxlength: 250, class: "form-control js-gfm-input", rows: 4

              .form-group
                .col-sm-2
                .col-sm-10
                  = image_tag group_icon(@group.to_param), alt: '', class: 'avatar s160'
                  %p.light
                    - if @group.avatar?
                      You can change your group avatar here
                    - else
                      You can upload an group avatar here
                  %a.choose-btn.btn.btn-small.js-choose-group-avatar-button
                    %i.icon-paper-clip
                    %span Choose File ...
                  &nbsp;
                  %span.file_name.js-avatar-filename File name...
                  = f.file_field :avatar, class: "js-group-avatar-input hidden"
                  .light The maximum file size allowed is 100KB.
                  - if @group.avatar?
                    %hr
                    = link_to 'Remove avatar', group_avatar_path(@group.to_param), data: { confirm: "Group avatar will be removed. Are you sure?"}, method: :delete, class: "btn btn-remove btn-small remove-avatar"

              .form-actions
                = f.submit 'Save group', class: "btn btn-save"

      .tab-pane#tab-projects
        .ui-box
          .title
            %strong= @group.name
            projects:
            - if can? current_user, :manage_group, @group
              %span.pull-right
                = link_to new_project_path(namespace_id: @group.id), class: "btn btn-tiny" do
                  %i.icon-plus
                  New Project
          %ul.well-list
            - @group.projects.each do |project|
              %li
                .list-item-name
                  = visibility_level_icon(project.visibility_level)
                  = link_to project.name_with_namespace, project
                .pull-right
                  = link_to 'Members', project_team_index_path(project), id: "edit_#{dom_id(project)}", class: "btn btn-small"
                  = link_to 'Edit', edit_project_path(project), id: "edit_#{dom_id(project)}", class: "btn btn-small"
                  = link_to 'Remove', project, data: { confirm: remove_project_message(project)}, method: :delete, class: "btn btn-small btn-remove"
            - if @group.projects.blank?
              .nothing-here-block This group has no projects yet

      .tab-pane#tab-remove
        .ui-box.ui-box-danger
          .title Remove group
          .body
            %p
              Removing group will cause all child projects and resources to be removed.
            %p
              %strong Removed group can not be restored!

            = link_to 'Remove Group', @group, data: {confirm: 'Removed group can not be restored! Are you sure?'}, method: :delete, class: "btn btn-remove"

app/views/groups/issues.html.haml
%h3.page-title
  Issues
  %span.pull-right #{@issues.total_count} issues

%p.light
  Only issues from
  %strong #{@group.name}
  group are listed here.
  - if current_user
    To see all issues you should visit #{link_to 'dashboard', issues_dashboard_path} page.
%hr

.row
  .col-md-3
    = render 'shared/filter', entity: 'issue'
  .col-md-9
    = render 'shared/issues'

app/views/groups/members.html.haml
- show_roles = should_user_see_group_roles?(current_user, @group)
%h3.page-title
  Group members
- if show_roles
  %p.light
    Members of group have access to all group projects.
    Read more about permissions
    %strong= link_to "here", help_permissions_path, class: "vlink"

%hr

.clearfix.js-toggle-container
  = form_tag members_group_path(@group), method: :get, class: 'form-inline member-search-form'  do
    .form-group
      = search_field_tag :search, params[:search], { placeholder: 'Find existing member by name', class: 'form-control search-text-input input-mn-300' }
    = submit_tag 'Search', class: 'btn'

  - if current_user && current_user.can?(:manage_group, @group)
    .pull-right
      = link_to '#', class: 'btn btn-new js-toggle-button' do
        Add members
        %i.icon-chevron-down

    .js-toggle-content.hide.new-group-member-holder
      = render "new_group_member"

.ui-box.prepend-top-20
  .title
    %strong #{@group.name}
    group members
    %small
      (#{@members.total_count})
  %ul.well-list
    - @members.each do |member|
      = render 'users_groups/users_group', member: member, show_roles: show_roles, show_controls: true
= paginate @members, theme: 'gitlab'

:coffeescript
  $('form.member-search-form').on 'submit', (event) ->
    event.preventDefault()
    Turbolinks.visit @.action + '?' + $(@).serialize()

app/views/groups/merge_requests.html.haml
%h3.page-title
  Merge Requests
  %span.pull-right #{@merge_requests.total_count} merge requests

%p.light
  Only merge requests from
  %strong #{@group.name}
  group are listed here.
  - if current_user
    To see all merge requests you should visit #{link_to 'dashboard', merge_requests_dashboard_path} page.
%hr
.row
  .col-md-3
    = render 'shared/filter', entity: 'merge_request'
  .col-md-9
    = render 'shared/merge_requests'

app/views/groups/new.html.haml
= form_for @group, html: { class: 'group-form form-horizontal' } do |f|
  - if @group.errors.any?
    .alert.alert-danger
      %span= @group.errors.full_messages.first
  .form-group
    = f.label :name, class: 'control-label' do
      Group name
    .col-sm-10
      = f.text_field :name, placeholder: "Ex. OpenSource", class: "form-control"

  .form-group.group-description-holder
    = f.label :description, "Details", class: 'control-label'
    .col-sm-10
      = f.text_area :description, maxlength: 250, class: "form-control js-gfm-input", rows: 4

  .form-group
    .col-sm-2
    .col-sm-10
      %ul
        %li A group is a collection of several projects
        %li Groups are private by default
        %li Members of a group may only view projects they have permission to access
        %li Group project URLs are prefixed with the group namespace
        %li Existing projects may be moved into a group

  .form-actions
    = f.submit 'Create group', class: "btn btn-create"

app/views/groups/show.html.haml
.dashboard
  .activities.col-md-8.hidden-sm.hidden-xs
    - if current_user
      = render "events/event_last_push", event: @last_push
      = link_to dashboard_path, class: 'btn btn-tiny' do
        &larr; To dashboard
      &nbsp;
    %span.cgray You will only see events from projects in this group
    %hr
    = render 'shared/event_filter'
    - if @events.any?
      .content_list
    - else
      .nothing-here-block Project activity will be displayed here
    = spinner
  .side.col-md-4
    .light-well.append-bottom-20
      = image_tag group_icon(@group.path), class: "avatar s90"
      .clearfix.light
        %h3.page-title
          = @group.name
        - if @group.description.present?
          %p= @group.description
    = render "projects", projects: @projects
    - if current_user
      .prepend-top-20
        = link_to group_path(@group, { format: :atom, private_token: current_user.private_token }), title: "Feed" do
          %strong
            %i.icon-rss
            News Feed

    %hr
    = render 'shared/promo'